export const searchTweetApiUrl = "https://api.twitter.com/2/search/adaptive.json"
export const getTokenUrl = "https://api.twitter.com/1.1/guest/activate.json"
export const twitterUserPageUrl = "https://twitter.com/"
export const mobileTwitterUserPageUrl = "https://mobile.twitter.com/"
export const getUserInfoUrl = "https://api.twitter.com/1.1/users/lookup.json"
export const getUserTwitterApiUrl = "https://api.twitter.com/2/timeline/profile/"
export const getFullTweetApiUrl = "https://api.twitter.com/2/timeline/conversation/"
export const tweetPageRegexUrl = new RegExp("https://twitter.com/.*/status/.*")
export const mobileTweetPageRegexUrl = new RegExp("https://mobile.twitter.com/.*/status/.*")